### ISSUE TITLE
netfetch linux binary. Below 22.04 seems to not be supported.

### ISSUE THREAD

**Issue by larssb** [deggja/netfetch#101]
# General info

First of, totally fair if this project do **NOT** want to support below 22.04. Then it would be great if this is mentioned in the docs. ( I can create a PR containing such a mention if this is a great idea ).

So e.g. executing `netfetch dash` gives:

```text
netfetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by netfetch)
netfetch: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by netfetch)
```

Looking into the issue I found:

- https://github.com/deggja/netfetch/blob/main/.github/workflows/release.yml#L14 < is pointing to Ubuntu latest. Which is certainly not 20.04 that I'm on
- At https://packages.ubuntu.com/search?keywords=libc6 we can see that v2.35 of libc is available on v22.04. So being above v2.34 we should be good - correct?
- I can't just upgrade to a later version on Ubuntu 20.04. Getting info that I'm already on latest of libc when trying

---

# Consequences

Because of this challenge I can't try out: https://github.com/deggja/netfetch/issues/48#issuecomment-1890054304 ... aka running the `netfetch` cli to try out the `Cilium Network Policies` scanning and generation.

---

# Sounding of

* Would below 22.04 Ubuntu versions be supported? ... or asked in another way, is libc at v2.34 a hard requirement for `netfetch`?

Thank you very much. This project and the idea of it is really great. Much needed.

**Comment by deggja** [comment]
Hello @larssb!
Thanks for submitting the issue. To be completely honest, I just have not thought about this scenario (as I've been running 22.04). I will look into what I can do to support older versions and let you know asap.

**Comment by deggja** [comment]
Hello @larssb!
The workflow has been changed to build for ubuntu 20.04 (which you are running). There is backwards compatibility, so it will still work fine on 22.04.

Can you test if it works for you now with the new [release](https://github.com/deggja/netfetch/releases/tag/3.2.3)?

**Comment by larssb** [comment]
Yes now it works .. I opened #115 as I was befuddled with the version still being reported to an older one after having upgraded `netfetch`.

Thank you for fixing this.
