### ISSUE TITLE
Feature request: ability to scan specific policy

### ISSUE THREAD

**Issue by deggja** [deggja/netfetch#108]
Description:

It would be very cool if the user could specify a singular policy to scan.

e.g: ```netfetch scan --target grafana-egress-network-policy```

This would then list the pods that this policy targets. It could also list some more information about what the policy actually does and how it applies to the pod.

**Comment by roopeshsn** [comment]
Are you planning on working on this? or I'll take it.

**Comment by deggja** [comment]
@roopeshsn I have been doing some work on this and I am planning to resume working on it. Stuck with some other assignments right now which has halted the progress here.

**Comment by roopeshsn** [comment]
> @roopeshsn I have been doing some work on this and I am planning to resume working on it. Stuck with some other assignments right now which has halted the progress here.

Cool

**Comment by deggja** [comment]
Initial logic for this implemented in #138.
