### ISSUE TITLE
Version is a constant so the same version is reported no matter the actual version.

### ISSUE THREAD

**Issue by larssb** [deggja/netfetch#115]
Here in the code: https://github.com/deggja/netfetch/blob/88a7580393fd0317f7709e76c48cf48797433f8e/backend/cmd/root.go#L10C1-L10C24 the version is a `constant`. So the same version will always be reported when using `netfetch version`. I don't know how to fix this in `go`.

Now "we" know.

Thank you for this great tool.

**Comment by deggja** [comment]
Thanks for creating this issue @larssb!
I am aware of this one. This was added as a placeholder back when netfetch was born and I never really got around to fix it. I will look into making this more dynamic.
