### ISSUE TITLE
Feature: relevant metrics in dashboard mode.

### ISSUE THREAD

**Issue by riuvshyn** [deggja/netfetch#144]
Hello, it would be great to have some relevant metrics exposed running netfetch in dashboard mode.

**Comment by deggja** [comment]
Hello @riuvshyn - thanks for the suggestion!

Can you explain a bit more in depth what you mean?
What kind of metrics were you thinking of?

**Comment by riuvshyn** [comment]
Hello @deggja, basically I wanted pretty much similar info that dashboard exposes to be exposed in prometheus metrics format, so using it people can create alerts for pods reported as not covered by net pols.

**Comment by deggja** [comment]
> Hello @deggja, basically I wanted pretty much similar info that dashboard exposes to be exposed in prometheus metrics format, so using it people can create alerts for pods reported as not covered by net pols.

Got it - thanks.
I believe this ties nicely into the existing issue on adding a prometheus endpoint here #127

**Comment by deggja** [comment]
Closing this issue. Work related to relevant metrics aka a prometheus endpoint will be linked and referenced in #127
