### ISSUE TITLE
Request - cleanup of binaries / assets committed to git

### ISSUE THREAD

**Issue by kgtw** [deggja/netfetch#151]
Hello, I'm interested in contributing to this repository. Currently, after cloning it, I noticed that its size exceeds 1GB, which seems excessive. This could pose an initial challenge for individuals with limited internet access or slower connection speeds.

Any chance that you can perform some maintenance to purge these files from git?

```
$ git clone git@github.com:deggja/netfetch.git
Cloning into 'netfetch'...
remote: Enumerating objects: 2071, done.
remote: Counting objects: 100% (190/190), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 2071 (delta 117), reused 162 (delta 102), pack-reused 1881
Receiving objects: 100% (2071/2071), 1.14 GiB | 3.39 MiB/s, done.
Resolving deltas: 100% (1341/1341), done.
```

**Comment by deggja** [comment]
Hello @kgtw,
Super cool that you want to contribute - you are very welcome to do so!
Also, thanks for pointing that out, was not aware. I will look into cleaning some of that up. For now, I think you can clone the git repo with the depth flag to reduce the size.
e.g:
```git clone https://github.com/deggja/netfetch.git --depth 1```

**Comment by luisgabrielroldan** [comment]
Hi! Just want to point that this also affects `brew` installs...

I just found your project, and was installing it when I found It was taking too long...

Hope you can have it fixed soon!

**Comment by deggja** [comment]
> Hi! Just want to point that this also affects `brew` installs...
> 
> 
> 
> I just found your project, and was installing it when I found It was taking too long...
> 
> 
> 
> Hope you can have it fixed soon!

Thanks for pointing that out. I will look at this asap.

**Comment by deggja** [comment]
@kgtw @luisgabrielroldan 
Repository has been cleaned up. From 1.2 GB in size to 17 MB 😅
Seems like the binary I use for testing has been pushed.. a lot of times. Added a gitignore so that will not happen again.

Thank you both for pointing this out. I rarely clone the repo down, since I already have it all locally so I had no idea haha.
