### ISSUE TITLE
Feature Request: Add a --kubeconfig parameter to give the path/name of a kubeconfig file to use

### ISSUE THREAD

**Issue by kastl-ars** [deggja/netfetch#163]
Thanks for this nice tool.

One thing that I think might be helpful, especially for people working with multiple clusters:

Add a `--kubeconfig` parameter to the CLI that accepts the name or path of a kubeconfig file to use. Most kubernetes-related tools have such a parameter, including `kubectl`.

**Comment by deggja** [comment]
> Thanks for this nice tool.
> 
> 
> 
> One thing that I think might be helpful, especially for people working with multiple clusters:
> 
> 
> 
> Add a `--kubeconfig` parameter to the CLI that accepts the name or path of a kubeconfig file to use. Most kubernetes-related tools have such a parameter, including `kubectl`.

Thanks for the request!
I am sure you know, albeit a bit tedious, the app looks for an environment variable OR the default kubeconfig, meaning you can specify the kubeconfig you want to use in the env variable to accomplish the same, but I get that its one extra step.

Thanks again for trying netfetch and contributing 🚀

**Comment by deggja** [comment]
Hello @kastl-ars,
The option to specify the path of the desired kubeconfig has been added in #202 and is included in version 0.5.4 of netfetch which was published just now.

**Comment by johanneskastl** [comment]
Thanks! I'll give it a spin next week!
