### ISSUE TITLE
App ignores KUBECONFIG env var and expects $HOME/.kube/config to exist instead

### ISSUE THREAD

**Issue by pslattery-wyn** [deggja/netfetch#26]
```shell
netfetch scan
It appears you are not connected to a Kubernetes cluster. Please check your kubeconfig.
Error during scan: stat /home/username/.kube/config: no such file or directory

echo $KUBECONFIG
/home/username/.kube/myclustername.config

# A workaround:
cp ~/.kube/myclustername.config ~/.kube/config
```

**Comment by deggja** [comment]
@pslattery-wyn Thanks for testing. I'm picking up this and making the kubeconfig check a bit more versatile.

**Comment by deggja** [comment]
@pslattery-wyn Implemented logic to check for a kubeconfig env variable. Should solve your error.

Homebrew tap has been updated with new changes. Feel free to verify that everything looks good for you.
