### ISSUE TITLE
There should be a default answer then running scan

### ISSUE THREAD

**Issue by pslattery-wyn** [deggja/netfetch#27]
When I run a scan against a local cluster it will prompt to add a default deny all policy to every namespace that has unprotected pods.  
For example:
```
netfetch scan                                   

Unprotected Pods found in namespace hello-world:
hello-world hello-world-manager-6564bd6bcf-8hfqg 10.232.4.217
? Do you want to add a default deny all network policy to the namespace hello-world? No
```

This should allow a default answer to be set from the CLI for unattended mode.
For example:
```
netfetch scan --add-default-deny=no

Unprotected Pods found in namespace hello-world:
hello-world hello-world-manager-6564bd6bcf-8hfqg 10.232.4.217
  Not adding a default deny all network policy to the namespace hello-world
```

**Comment by deggja** [comment]
Hello @pslattery-wyn!

Thank you for the feedback.

I think what you're getting at is that is should be possible to run `netfetch scan` without being prompted to add a network policy. Right?

Thats a good idea. I will look into implementing that asap. Also, you should be able to do this using the `netfetch dash` command. The table will list all untargeted workloads in the cluster/namespace without the need for any prompt.

**Comment by deggja** [comment]
Added the ability to use --dryrun or -d to avoid being prompted about adding network policies to the cluster.

https://github.com/deggja/netfetch/commit/c1128d30e0df8d07470d7c1344fedd4d49b7ff73

Does this fit what you were thinking of @pslattery-wyn?

You can test this feature in the newest version. LMK if I can close this.

**Comment by deggja** [comment]
I will close this issue as completed for now. Please re-open if you deem it neccessary @pslattery-wyn
