### ISSUE TITLE
Feature: implement tests

### ISSUE THREAD

**Issue by deggja** [deggja/netfetch#46]
theres currently no tests in place for the code, this should be implemented.

**Comment by roopeshsn** [comment]
Hi, @deggja! I am interested in working on this issue. As a first step, for which functions should I write tests? It'll be helpful if you share your thought process.

**Comment by roopeshsn** [comment]
Also, there are testing frameworks in Go that mock K8s cluster so that we can create resources in the mock to test whether the desired outcomes are met. @deggja

**Comment by deggja** [comment]
Hello @roopeshsn!
Brilliant. I am super happy to hear that you want to contribute here. Help is welcomed with open arms. As far as this issue goes and writing tests for the code, theres nothing in place as of today - so we would essentially need to write tests for all core functions. As far as using a testing framework goes, I am all ears and open to suggestions.

I will go through the code the in the next few days and write up a list of which functions you can prioritize/start with. Sound good?

**Comment by roopeshsn** [comment]
> Hello @roopeshsn! Brilliant. I am super happy to hear that you want to contribute here. Help is welcomed with open arms. As far as this issue goes and writing tests for the code, theres nothing in place as of today - so we would essentially need to write tests for all core functions. As far as using a testing framework goes, I am all ears and open to suggestions.
> 
> I will go through the code in the next few days and write up a list of which functions you can prioritise/start with. Sound good?

Yes, it sounds good!

**Comment by deggja** [comment]
> > Hello @roopeshsn! Brilliant. I am super happy to hear that you want to contribute here. Help is welcomed with open arms. As far as this issue goes and writing tests for the code, theres nothing in place as of today - so we would essentially need to write tests for all core functions. As far as using a testing framework goes, I am all ears and open to suggestions.
> > I will go through the code in the next few days and write up a list of which functions you can prioritise/start with. Sound good?
> 
> Yes, it sounds good!

I think for starters. The obvious big ones are the scanning functions. That would be:

```golang
ScanNetworkPolicies # scanner.go
ScanCiliumNetworkPolicies # cilium-scanner.go
ScanCiliumClusterwideNetworkPolicies # cilium-scanner.go
```
In addition to those, the dashboard specific functions:

```golang
gatherVisualizationData # visualizer.go
GatherClusterVisualizationData # visualizer.go
getNetworkPolicyYAML # visualizer.go
```
I think starting with these would make sense. Once tests for these are in place, we can move on to the rest of the logic.

**Comment by roopeshsn** [comment]
Thanks! The `ScanNetworkPolicies` function have CLI interaction in-between. I am thinking how we can handle that.

**Comment by deggja** [comment]
> Thanks! The `ScanNetworkPolicies` function have CLI interaction in-between. I am thinking how we can handle that.

Hmm. Yes. You will find that all the scanners have CLI logic in them. I have thought about taking them apart and splitting them up into smaller and separate functions, but I have not gotten to that yet.

I think theres three options;

1. Write tests for the parts of the functions that makes sense.
2. Start writing tests for other less complex functions.
3. Start rewriting the functions and split CLI logic into separate functions (this is definately a separate issue in itself..)

Disclaimer: I have not looked into writing tests yet, so not completely sure what it entails. Especially concerning the CLI logic. I can look more into this in the next few days and share my thoughts sometime this weekend.

What do you think? What are your thoughts on this?

**Comment by roopeshsn** [comment]
Alright, I'll also look into how we can write tests for scanner functions. In the meantime, I'll start writing tests for dashboard specific functions.

**Comment by roopeshsn** [comment]
Hi @deggja! I wrote a test for `gatherVisualizationData` function. The test function I wrote will create a fake clientset from [fake](https://pkg.go.dev/k8s.io/client-go/kubernetes/fake) library and create a pod and a networkpolicy. Then we can pass this fake clientset to the `gatherVisualizationData` function so that it will return the `VisualizationData` struct. We can compare both results. 

Now the `gatherVisualizationData` function creates a clientset. We need to remove that line and pass the clientset as an argument. So that when we run the test we'll pass the fake clientset. Can I make that change?

**Comment by deggja** [comment]
> Hi @deggja! I wrote a test for `gatherVisualizationData` function. The test function I wrote will create a fake clientset from [fake](https://pkg.go.dev/k8s.io/client-go/kubernetes/fake) library and create a pod and a networkpolicy. Then we can pass this fake clientset to the `gatherVisualizationData` function so that it will return the `VisualizationData` struct. We can compare both results. 
> 
> 
> 
> Now the `gatherVisualizationData` function creates a clientset. We need to remove that line and pass the clientset as an argument. So that when we run the test we'll pass the fake clientset. Can I make that change?

Nice, sounds good. Make the required changes. I can help you test in your branch once its in place if you need it.

**Comment by roopeshsn** [comment]
I'm done with writing tests for `visualizer.go`. Shall I proceed with refactoring `scanner.go`, so that I can write a test for `ScanNetworkPolicies`?

**Comment by deggja** [comment]
> I'm done with writing tests for `visualizer.go`. Shall I proceed with refactoring `scanner.go`, so that I can write a test for `ScanNetworkPolicies`?

Very nice!
You can. However, there are other functions and helper functions in scanner.go that might be easier to start with if you want.

**Comment by roopeshsn** [comment]
Done with writing tests for helper functions in `scanner.go`. I'll start by doing the same for `cilium-scanner.go`.

**Comment by roopeshsn** [comment]
Now, the remaining functions to write tests are the main ones,
- ScanNetworkPolicies
- ScanCiliumNetworkPolicies

How we can proceed with them?

**Comment by deggja** [comment]
> Now, the remaining functions to write tests are the main ones,
> 
> * ScanNetworkPolicies
> * ScanCiliumNetworkPolicies
> 
> How we can proceed?

Hey @roopeshsn!
Great job so far, its looking good.
I have had to take some time off due to some personal reasons, so have not had time to look at all your commits yet. Hopefully I'll get time to do so in the near future.

Considering the task involving refactoring the main functions is quite tedious, maybe it makes sense to write tests for the non-CLI parts of those functions for the time being? We can rewrite the tests at a later stage, once the main functions have been rewritten as well.

Thoughts?

**Comment by roopeshsn** [comment]
> > Now, the remaining functions to write tests are the main ones,
> > 
> > * ScanNetworkPolicies
> > * ScanCiliumNetworkPolicies
> > 
> > How we can proceed?
> 
> Hey @roopeshsn! Great job so far, its looking good. I have had to take some time off due to some personal reasons, so have not had time to look at **all** your commits yet (but I have skimmed through). Hopefully I'll get time to do so in the near future.
> 
> Considering the task involving refactoring the main functions is quite tedious, maybe it makes sense to write tests for the non-CLI parts of those functions for the time being? We can rewrite the tests at a later stage, once the main functions have been rewritten as well.
> 
> Thoughts?

Sure
